services:
  database:
    image: "postgres:16.1"
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - ACCEPT_EULA=y
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=testPassword123
      - POSTGRES_DB=TrainDB